### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by markdavidlee15** [sveale/remote-edit#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.14

### Stack Trace

Uncaught URIError: URI malformed

```
At C:\Users\MarkDavidLee\.atom\packages\remote-edit\lib\main.coffee:133

URIError: URI malformed
  at decodeURIComponent (native)
  at C:\Users\MarkDavidLee\.atom\packages\remote-edit\lib\main.coffee:133:68
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\MarkDavidLee\AppData\Local\atom\app-1.0.4\resources\app.asar\src\workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (C:\Users\MarkDavidLee\AppData\Local\atom\app-1.0.4\resources\app.asar\src\workspace.js:379:19)
  at C:\Users\MarkDavidLee\.atom\packages\remote-edit\lib\view\files-view.coffee:189:26
  at C:\Users\MarkDavidLee\.atom\packages\remote-edit\lib\view\files-view.coffee:180:49
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -3:11.9.0 remote-edit:new-host-sftp (atom-text-editor.editor)
  3x -2:32.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:44.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -1:41.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:29 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:29 core:cancel (atom-text-editor.editor.is-focused)
  3x -1:27.4.0 editor:move-to-previous-subword-boundary (atom-text-editor.editor.is-focused)
     -1:24 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:21.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:21.3.0 remote-edit:browse (atom-text-editor.editor)
     -1:20.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:54.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:43 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43 remote-edit:browse (atom-text-editor.editor)
     -0:41.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
emmet, v2.3.12
remote-edit, v1.8.14

# Dev
No dev packages
```

**Comment by petervansark** [comment]
Uncaught URIError: URI malformed

URIError: URI malformed
  at decodeURIComponent (native)
  at C:\Users\Peter\.atom\packages\remote-edit\lib\main.coffee:133:68
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\Peter\AppData\Local\atom\app-1.0.4\resources\app.asar\src\workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (C:\Users\Peter\AppData\Local\atom\app-1.0.4\resources\app.asar\src\workspace.js:379:19)
  at C:\Users\Peter\.atom\packages\remote-edit\lib\view\files-view.coffee:189:26
  at C:\Users\Peter\.atom\packages\remote-edit\lib\view\files-view.coffee:180:49
  at FSReqWrap.oncomplete (fs.js:77:15)

## Repro Steps

1. open file to edit


**Expected:** [Enter expected behavior here]
**Actual:** [Enter actual behavior here]

## Command History

```
  8x -1:01.3 core:backspace (atom-text-editor.editor.mini)
     -0:53.1 command-palette:toggle (atom-text-editor.editor.mini)
     -0:50.3 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:50.3 remote-edit:browse (atom-text-editor.editor.mini)
  3x -0:48.9 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:48.1 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:47.1 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:42.3 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.0 command-palette:toggle (a.stack-toggle)
     -0:19.6 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:18.2 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:18.2 bug-report:insert-version-info (a.stack-toggle)
     -0:14.1 command-palette:toggle (a.stack-toggle)
     -0:02.7 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 bug-report:open (a.stack-toggle)
```

## Versions

* **Atom:**       1.0.4
* **Atom-Shell:** 0.22.3
* **OS:**         Microsoft Windows 8.1
* **Misc**
    * apm  1.0.1
    * npm  2.5.1
    * node 0.10.35
    * python 
    * git 1.9.5.github.0
    * visual studio 2010

**Comment by sveale** [comment]
This is difficult for me to debug without having the actual URI that can't be decoded.
Could either of you insert "console.debug(query)" below line 133 in main.coffe and send me the result? Be sure to sanitize any passwords/IPs. You can either post the result here or send it to me at sverre.aleksandersen (at) gmail.com.

**Comment by petervansark** [comment]
I've send an email with results from the console.

**Comment by sveale** [comment]
Can y'all try out the newest version and tell me if this is fixed?

**Comment by branderjeremy** [comment]
@sveale Still erroring out.

**Comment by sveale** [comment]
I'm afraid I haven't been able to reproduce the issue @branderjeremy . 
I've gotten quite a bit of info from @petervansark but haven't been able to figure it out. 
Are you also using a windows version >= 8?

**Comment by branderjeremy** [comment]
@sveale sorry, I'm on Mac OS X. What information can I provide to help you out?

**Comment by isaaclong** [comment]
Was this issue ever resolved? I'm having the same problem when opening files.

Atom version: 1.3.2
System: OS X El Capitan 10.11.2

![screen shot 2015-12-17 at 10 21 54 pm](https://cloud.githubusercontent.com/assets/5703342/11890749/a4d0e34a-a50c-11e5-9048-fe115751dbaf.png)

Stack Trace:

URIError: URI malformed
    at decodeURIComponent (native)
    at /Users/isaaclong/.atom/packages/remote-edit/lib/main.coffee:139:44
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:454:22)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at /Users/isaaclong/.atom/packages/remote-edit/lib/view/files-view.coffee:188:26
    at /Users/isaaclong/.atom/packages/remote-edit/lib/model/sftp-host.coffee:165:9
    at /Users/isaaclong/.atom/packages/remote-edit/lib/model/sftp-host.coffee:161:76
    at /Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:1053:21
    at SFTPStream._transform (/Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:383:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:173:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SFTPStream.Writable.write (_stream_writable.js:207:11)
    at Channel.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Channel.Readable.push (_stream_readable.js:110:10)
    at SSH2Stream.<anonymous> (/Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/lib/Channel.js:142:15)
    at emitOne (events.js:77:13)
    at SSH2Stream.emit (events.js:169:7)
    at parsePacket (/Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3166:10)
    at SSH2Stream._transform (/Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/isaaclong/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)

**Comment by sveale** [comment]
No this issue has, unfortunately, not been resolved. I was never able to reproduce the issue. I am working on refactoring the code to change the way remote files are opened (without using a custom URI scheme) which I believe will resolve it, but it's difficult to say when I'm not able to reproduce it.

**Comment by schlauberg** [comment]
Hi,
Same problem:
MacOS 10.12 Beta (16A201w)
Atom 1.8.0
Community Packages (8) /Users/achimh/.atom/packages
├── aesthetic-ui@2.0.0
├── git-time-machine@1.5.3
├── linter@1.11.11
├── linter-rails-best-practices@0.2.2
├── linter-ruby@1.2.2
├── linter-ruby-reek@1.5.1
├── remote-edit@1.8.24
└── ruby-block@0.3.5
Remote site:
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

user: root@hostname
directory /etc/php/php-fpm.d
trying to open file www.conf

The issue also comes up if I start from a different directory and go there via ".." ".." ....

Very reliably reproducible. I'm happy to be of any help for looking into that issue.

Best

Achim

**Comment by schlauberg** [comment]
My guess is that it is an permission issue. The same site works with other users, but root can't open one thing :P. I'm willing to help you to resolve this, in case you are up for it, maybe we can reproduce it.

Best

Achim

**Comment by Profeten** [comment]
I am also experiencing this problem and I have checked premissions and they are set at u+rwx for the user I am currently in session with.
Let me know if I can help you guys out in finding out what this is about, I really enjoy working with Atom but recently there's been a bit of sublime since I have to get code going!
