### ISSUE TITLE
Uncaught Error: Protocol version not supported

### ISSUE THREAD

**Issue by bzx** [sveale/remote-edit#112]
1. Trying to connect to my host which supports both FTP and SFTP (but I can't connect using this plugin with SFTP anyway)
2. Typed port 21
3. After connection attempt, the error appears

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.15

### Stack Trace

Uncaught Error: Protocol version not supported

```
At events.js:141

Error: Protocol version not supported
  at SSH2Stream._transform (/Users/bzx/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:376:25)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/bzx/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SSH2Stream.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -3:12 hostview:edit (atom-text-editor.editor.mini.is-focused)
     -3:10.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -3:10.2.0 editor:move-to-end-of-word (atom-text-editor.editor.mini.is-focused)
  3x -3:09.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -3:09.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:52.7.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-chester-atom-syntax.theme-one-light-ui)
     -0:50.6.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
  2x -0:47.6.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-chester-atom-syntax.theme-one-light-ui)
     -0:30.9.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
     -0:23.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:22.3.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-chester-atom-syntax.theme-one-light-ui)
     -0:11.1.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
     -0:09.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
  2x -0:08.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-chester-atom-syntax.theme-one-light-ui)
     -0:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "themes": [
      "one-light-ui",
      "chester-atom-syntax"
    ]
  },
  "remote-edit": {
    "showHiddenFiles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.10
autocomplete-sass, v0.1.0
bezier-curve-editor, v0.7.2
chester-atom-syntax, v0.1.1
emmet, v2.3.12
file-icons, v1.6.3
pigments, v0.9.3
project-manager, v1.15.11
react, v0.12.6
remote-edit, v1.8.15
save-session, v0.15.7
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by sveale** [comment]
Is your SSH server running on port 21? Thats usually used for FTP. SSH normally uses port 22.

**Comment by bzx** [comment]
It wasn't SSH, I was trying to connect using FTP protocol, so port is 21. But now it does connect with no errors. Thanks
