### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by ruvasik** [sveale/remote-edit#113]
[Enter steps to reproduce below:]

1. Try open file as root
2. ...

**Atom Version**: 1.0.6
**System**: Mac OS X 10.11
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.15

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:207

TypeError: path must be a string
    at TypeError (native)
    at fs.exists (fs.js:207:11)
    at Object.fs.exists (ATOM_SHELL_ASAR.js:286:16)
    at /Users/ruvasik/.atom/packages/remote-edit/lib/model/sftp-host.coffee:154:25
    at fn (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:369:17)
```

### Commands

```
     -0:02.2.0 remote-edit:browse (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-atom"
    ]
  },
  "remote-edit": {
    "foldersOnTop": true,
    "rememberLastOpenDirectory": true,
    "showHiddenFiles": true
  }
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.15

# Dev
No dev packages
```

**Comment by sveale** [comment]
Please provide more information about how error is triggered and what you've done to try and remedy it.
