### ISSUE TITLE
Uncaught Error: Malformed private key (expected sequence). Bad passphrase?

### ISSUE THREAD

**Issue by NeckBeardPrince** [sveale/remote-edit#121]
[Enter steps to reproduce below:]

1. This key works fine in Sublime Text, I don't have a passphrase
2. Key is RSA

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.15

### Stack Trace

Uncaught Error: Malformed private key (expected sequence). Bad passphrase?

```
At /Users/Adam/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/utils.js:307

Error: Malformed private key (expected sequence). Bad passphrase?
  at genPublicKey (/Users/Adam/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/utils.js:307:13)
  at Client.connect (/Users/Adam/.atom/packages/remote-edit/node_modules/ssh2/lib/client.js:156:29)
  at /Users/Adam/.atom/packages/remote-edit/lib/model/sftp-host.coffee:116:23
  at fn (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:638:34)
  at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:554:34)
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
 18x -6:54.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -3:51.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  7x -3:49 blur (atom-text-editor.editor.mini.is-focused)
     -2:47 fuzzy-finder:toggle-git-status-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-material-ui)
     -2:44.3.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-material-ui)
     -2:43.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -2:43.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -2:18.6.0 core:cancel (a.btn-issue.btn.btn-error)
  2x -2:17.9.0 blur (a.btn-issue.btn.btn-error)
     -1:09.2.0 remote-edit:browse (div.package-readme.native-key-bindings)
     -1:09.2.0 blur (div.package-readme.native-key-bindings)
     -1:08.4.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
 21x -1:08.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-material-ui)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:01.3.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "minimap",
      "vim-mode"
    ]
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-commander, v0.3.0
atom-material-ui, v0.6.0
file-icons, v1.6.9
language-ansible, v0.1.3
language-dots, v0.0.4
language-hcl, v0.1.0
language-tmux, v0.4.0
linter, v1.4.3
linter-ansible-lint, v0.0.7
linter-js-yaml, v1.1.1
linter-jsonlint, v0.1.4
linter-ruby, v1.0.2
project-manager, v1.16.0
remote-edit, v1.8.15
set-syntax, v0.3.0
seti-syntax, v0.4.0
ssh-config, v0.10.1

# Dev
No dev packages
```

**Comment by sveale** [comment]
Have you selected "User Agent" or "Private key"  as auth method? If it's the latter, have you checked that a space or something like that haven't crept inside the passphrase field?

**Comment by sveale** [comment]
This seems like an issue with the underlying SSH module remote-edit uses. Looks similar to https://github.com/mscdex/ssh2/issues/244.

**Comment by purefan** [comment]
For anyone else running into this issue or something similar, I entered the wrong hostname and got this same issue, the fix is of course to use the correct hostname for the private key.

**Comment by InstanceOfMichael** [comment]
This is still happening for me.

**Comment by xezpeleta** [comment]
Same here on Ubuntu 15.10

**Comment by djneely** [comment]
I'm experiencing the same issue with a passphrase-less key.
