### ISSUE TITLE
Uncaught Error: Protocol error: expected packet type 32, got 90

### ISSUE THREAD

**Issue by ruvasik** [sveale/remote-edit#125]
[Enter steps to reproduce below:]

1. Simple saving file..

**Atom Version**: 1.0.11
**System**: Mac OS X 10.11
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.18

### Stack Trace

Uncaught Error: Protocol error: expected packet type 32, got 90

```
At events.js:141

Error: Protocol error: expected packet type 32, got 90
  at onDISCONNECT (/Users/ruvasik/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2034:15)
  at SSH2Stream.<anonymous> (/Users/ruvasik/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:179:5)
  at emitMany (events.js:108:13)
  at SSH2Stream.emit (events.js:179:7)
  at parsePacket (/Users/ruvasik/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3464:10)
  at SSH2Stream._transform (/Users/ruvasik/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/ruvasik/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SSH2Stream.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
  2x -0:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:07.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:07.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:05.6.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:05.0 core:cut (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:03.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:03.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:03.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "metrics"
    ]
  },
  "remote-edit": {
    "foldersOnTop": true,
    "rememberLastOpenDirectory": true,
    "showHiddenFiles": true,
    "notifications": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
emmet, v2.3.12
remote-atom, v1.2.7
remote-edit, v1.8.18

# Dev
No dev packages
```

**Comment by sveale** [comment]
Does this occur with multiple files? Have you tried different servers? Tried uninstalling remote-edit?
Unfortunately, I'm not able to reproduce this on my setup.
