### ISSUE TITLE
Uncaught Error: Malformed private key (expected integer for version)

### ISSUE THREAD

**Issue by cwramsey** [sveale/remote-edit#127]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.18

### Stack Trace

Uncaught Error: Malformed private key (expected integer for version)

```
At /Users/chrisramsey/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/utils.js:163

Error: Malformed private key (expected integer for version)
  at genPublicKey (/Users/chrisramsey/.atom/packages/remote-edit/node_modules/ssh2/node_modules/ssh2-streams/lib/utils.js:163:15)
  at Client.connect (/Users/chrisramsey/.atom/packages/remote-edit/node_modules/ssh2/lib/client.js:156:29)
  at /Users/chrisramsey/.atom/packages/remote-edit/lib/model/sftp-host.coffee:116:23
  at fn (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:638:34)
  at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:554:34)
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
     -1:59.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:51.4.0 remote-edit:browse (atom-text-editor.editor.is-focused)
     -1:50.5.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
  2x -1:49 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:41 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:33.3.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
  4x -1:31.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:30.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:27.7.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:24.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:01.2.0 remote-edit:browse (a.btn-issue.btn.btn-error)
     -1:00.1.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
  3x -0:57.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.8.0 remote-edit:browse (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-typescript"
    ]
  },
  "remote-edit": {
    "foldersOnTop": true,
    "rememberLastOpenDirectory": true,
    "showHiddenFiles": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-jade, v0.3.0
autoclose-html, v0.18.0
language-ejs, v0.2.0
language-rust, v0.4.3
linter, v1.2.4
linter-php, v1.0.3
meteor-api, v2.20.0
remote-edit, v1.8.18

# Dev
No dev packages
```

**Comment by sveale** [comment]
What kind of key are you using?
