### ISSUE TITLE
Failed to load the remote-edit package

### ISSUE THREAD

**Issue by lvnilesh** [sveale/remote-edit#129]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.20

### Stack Trace

Failed to load the remote-edit package

```
At Cannot find module 'serializable'

Error: Cannot find module 'serializable'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/cloudgenius/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:20:18)
    at Object.<anonymous> (/Users/cloudgenius/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:255:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
emmet, v2.3.12
highlight-selected, v0.10.1
remote-edit, v1.8.20

# Dev
No dev packages
```

**Comment by sveale** [comment]
Have you tried reinstalling the package?

**Comment by lvnilesh** [comment]
no I just uninstalled it. I will install it again.

**Comment by sveale** [comment]
Did it resolve the issue?

**Comment by netpalantir** [comment]
Same here, fresh install on Atom 1.1.0-beta 1

**Comment by gmemstr** [comment]
I can confirm that reinstalling it does not fix the issue.

**Comment by sveale** [comment]
If anyone still having issues with this, it might be related to #143 which should now be resolved.

**Comment by gmemstr** [comment]
@sveale I posted my issue separately, it was #138, which you resolved.

**Comment by sveale** [comment]
@gmemstr allright thanks. I'll close this issue also then :)
