### ISSUE TITLE
Uncaught Error: Cannot find module 'osenv'

### ISSUE THREAD

**Issue by Kulkow** [sveale/remote-edit#131]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.21

### Stack Trace

Uncaught Error: Cannot find module 'osenv'

```
At module.js:336

Error: Cannot find module 'osenv'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (D:\Users\Пользователь\.atom\packages\remote-edit\lib\model\host.coffee:6:9)
  at Object.<anonymous> (D:\Users\Пользователь\.atom\packages\remote-edit\lib\model\host.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (D:\Users\Пользователь\.atom\packages\remote-edit\lib\view\host-view.coffee:4:8)
  at Object.<anonymous> (D:\Users\Пользователь\.atom\packages\remote-edit\lib\view\host-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.newHostFtp (D:\Users\Пользователь\.atom\packages\remote-edit\lib\main.coffee:90:17)
  at atom-workspace.<anonymous> (D:\Users\Пользователь\.atom\packages\remote-edit\lib\main.coffee:77:73)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at EventEmitter.<anonymous> (D:\Users\Пользователь\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -0:03.8.0 remote-edit:new-host-ftp (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "atom-message-panel-service",
      "jslint"
    ]
  },
  "remote-edit": {
    "showHiddenFiles": true
  }
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.21

# Dev
No dev packages
```

**Comment by sveale** [comment]
Try reinstalling the package.
