### ISSUE TITLE
Uncaught Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by Josetkd** [sveale/remote-edit#139]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.22

### Stack Trace

Uncaught Error: Cannot find module 'moment'

```
At module.js:336

Error: Cannot find module 'moment'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\diseño-grafico\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\diseño-grafico\.atom\packages\remote-edit\lib\view\open-files-view.coffee:8:10)
  at Object.<anonymous> (C:\Users\diseño-grafico\.atom\packages\remote-edit\lib\view\open-files-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\diseño-grafico\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.showOpenFiles (C:\Users\diseño-grafico\.atom\packages\remote-edit\lib\main.coffee:102:22)
  at atom-workspace.<anonymous> (C:\Users\diseño-grafico\.atom\packages\remote-edit\lib\main.coffee:74:76)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\diseño-grafico\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (C:\Users\diseño-grafico\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\diseño-grafico\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (C:\Users\diseño-grafico\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -8:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:56.8.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -5:55.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:53.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:47.1.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -4:10.1.0 remote-edit:new-host-sftp (div.package-detail.panels-item)
     -2:58.9.0 application:add-project-folder (div.package-detail.panels-item)
  2x -2:40.8.0 remote-edit:new-host-ftp (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 15x -1:58.4.0 remote-edit:browse (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -1:49.5.0 remote-edit:show-open-files (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

```json
{
  "core": {},
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.22

# Dev
No dev packages
```

**Comment by sveale** [comment]
Try reinstalling the package.
