### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by ArielSaldana** [sveale/remote-edit#140]
[Enter steps to reproduce below:]

Error occurs when trying to connect to stfp with a ppk file.

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.22

### Stack Trace

Uncaught TypeError: object is not a function

```
At C:\Users\systems\.atom\packages\remote-edit\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:475

TypeError: object is not a function
  at Object.convertPPKPrivate (C:\Users\systems\.atom\packages\remote-edit\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:475:14)
  at module.exports (C:\Users\systems\.atom\packages\remote-edit\node_modules\ssh2\node_modules\ssh2-streams\lib\keyParser.js:187:13)
  at Client.connect (C:\Users\systems\.atom\packages\remote-edit\node_modules\ssh2\lib\client.js:145:23)
  at C:\Users\systems\.atom\packages\remote-edit\lib\model\sftp-host.coffee:124:23
  at fn (C:\Users\systems\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:638:34)
  at Immediate._onImmediate (C:\Users\systems\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:554:34)
  at processImmediate [as _immediateCallback] (timers.js:371:17)

```

### Commands

```
     -4:21.9.0 remote-edit:new-host-sftp (ul.list-inline.tab-bar.inset-panel)
  2x -3:54.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:21.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:17.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:07.6.0 remote-edit:browse (ul.list-inline.tab-bar.inset-panel)
     -1:26.8.0 settings-view:open (atom-pane.pane.active)
     -0:05.6.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
build, v0.48.0
remote-edit, v1.8.22

# Dev
No dev packages
```

**Comment by sveale** [comment]
What kind of key is it? Have you looked at #72?
