### ISSUE TITLE
Uncaught (in promise) Error: Must pass a config parameter when constructing TextEditors

### ISSUE THREAD

**Issue by nobuhito** [sveale/remote-edit#142]
```
Uncaught (in promise) Error: Must pass a config parameter when constructing TextEditors
    at RemoteEditEditor.TextEditor [as constructor] (C:\Users\XXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\text-editor.js:89:15)
    at new RemoteEditEditor (file:///C:/Users/XXXXX/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:25:7)
    at file:///C:/Users/XXXXX/.atom/packages/remote-edit/lib/main.coffee:141:24
    at process._tickCallback (node.js:368:9)
```

**Comment by nobuhito** [comment]
This is same as #143 closing
