### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deletePassword' of undefined

### ISSUE THREAD

**Issue by mandavister** [sveale/remote-edit#160]
Directly after trying to add a new sftp host with Atom 1.3.2 and remote-edit 1.8.23:

TypeError: Cannot read property 'deletePassword' of undefined
    at HostView.module.exports.HostView.confirm (/home/butze/.atom/packages/remote-edit/lib/view/host-view.coffee:139:19)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by buffer51** [comment]
Got the same error with Atom 1.4.0 & remote-edit 1.8.23. Any updates on this?

**Atom Version**: 1.4.0
**System**: Ubuntu 14.04.3
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.23


### Stack Trace

Uncaught TypeError: Cannot read property 'deletePassword' of undefined

```
At /home/paul/.atom/packages/remote-edit/lib/view/host-view.coffee:139

TypeError: Cannot read property 'deletePassword' of undefined
    at HostView.module.exports.HostView.confirm (/home/paul/.atom/packages/remote-edit/lib/view/host-view.coffee:139:19)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -6:55.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:17.3.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -3:04.0 remote-edit:browse (atom-text-editor.editor.is-focused)
     -2:54.4.0 remote-edit:new-host-sftp (atom-text-editor.editor.is-focused)
     -2:27.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:40.9.0 remote-edit:new-host-sftp (div.package-detail.panels-item)
     -0:47.1.0 remote-edit:show-open-files (a.btn-issue.btn.btn-error)
     -0:43.6.0 remote-edit:browse (atom-text-editor.editor.mini.is-focused)
     -0:40.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:20.6.0 remote-edit:new-host-sftp (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-clang"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "remote-edit": {
    "storePasswordsUsingKeytar": true
  }
}
```

### Installed Packages

```coffee
# User
ctrl-dir-scroll, v0.2.2
language-matlab, v0.2.0
markdown-scroll-sync, v2.0.3
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
remote-edit, v1.8.23
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by Rhogit** [comment]
Still having this issue on Ubuntu 16.04 LTS
I am on AWS, so no passphrase

**Comment by skilfullycurled** [comment]
I was setting up Atom on a new machine (details below) and received this error as well when adding a new sftp host with private key and no passphrase.  The version of node-keytar I have installed is keytar@4.0.4.  For what it's worth, I do not have this issue on my other machine which is Atom: 1.14.3 x64, Electron: 1.3.13, OS: Mac OS X 10.11.5.


**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0


### Stack Trace

Uncaught TypeError: Cannot read property 'deletePassword' of undefined

```
At /Users/bsugar/.atom/packages/remote-edit/lib/view/host-view.coffee:139

TypeError: Cannot read property 'deletePassword' of undefined
    at HostView.module.exports.HostView.confirm (/packages/remote-edit/lib/view/host-view.coffee:139:19)
    at /packages/remote-edit/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/remote-edit/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/remote-edit/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -1:32.7.0 remote-edit:browse (input.hidden-input)
     -1:08.4.0 core:move-down (input.hidden-input)
     -1:06.9.0 hostview:edit (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
file-type-icons 1.3.4 
highlight-selected 0.13.1 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
pretty-json 1.6.4 
remote-edit 1.9.0 
remove-whitespace 0.2.1 
termination 0.5.1 
```

**Comment by psgprsh** [comment]
I filled the passphrase with "" (double-quote) and it works!

**Comment by cromefire** [comment]
Still an existing bug, workaround results in invalid key format
