### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by guntisratkevics** [sveale/remote-edit#195]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: 'remote-edit' package, vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'alias' of undefined

```
At /Users/guntisr/.atom/packages/remote-edit/lib/model/host.coffee:62

TypeError: Cannot read property 'alias' of undefined
    at SftpHost.module.exports.Host.getSearchKey (/Users/guntisr/.atom/packages/remote-edit/lib/model/host.coffee:34:63)
    at /Users/guntisr/.atom/packages/remote-edit/lib/model/host.coffee:18:9
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at SftpHost.Host (/Users/guntisr/.atom/packages/remote-edit/lib/model/host.coffee:17:19)
    at new SftpHost (/Users/guntisr/.atom/packages/remote-edit/lib/model/sftp-host.coffee:32:7)
    at Object.module.exports.newHostSftp (/Users/guntisr/.atom/packages/remote-edit2/lib/main.coffee:109:16)
    at atom-workspace.<anonymous> (/Users/guntisr/.atom/packages/remote-edit2/lib/main.coffee:94:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1104:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -1:45.5.0 remote-edit:new-host-sftp (atom-text-editor.editor.is-focused)
     -1:27.9.0 settings-view:check-for-package-updates (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
remote-edit2, v3.0.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Nollikino** [comment]
I have no issues adding new hosts for SFTP. Could you please specify the steps to reproduce this problem?

Furthermore because there is some issues after some deprecated commands after Atom-Version 1.9.x this is how it's set up on my side:
Atom Version 1.9.9
remote-edit@1.8.24. I've also manually changed my files according to the pull-request #187.

**Comment by boubouhkarim** [comment]
i have the same issue with atom Version 1.9.9

**Comment by Nollikino** [comment]
@boubouhkarim Could you please specify the steps to reproduce this problem? It's not specified in the original Issue, and it seems I cannot reproduce it.

**Comment by yzhao30** [comment]
I have the same issue. I freshly installed atom 1.9.9 on ubuntu 16.04 and install the package from the atom interface. The error occurs when adding new host

**Comment by yzhao30** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Ubuntu 16.04.1
**Thrown From**: [remote-edit2](https://github.com/duxet/remote-edit2) package, v3.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'alias' of undefined

```
At /home/yzhao/.atom/packages/remote-edit2/lib/model/host.coffee:34

TypeError: Cannot read property 'alias' of undefined
    at FtpHost.module.exports.Host.getSearchKey (/home/yzhao/.atom/packages/remote-edit2/lib/model/host.coffee:34:63)
    at /home/yzhao/.atom/packages/remote-edit2/lib/model/host.coffee:18:9
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:141:21)
    at FtpHost.Host (/home/yzhao/.atom/packages/remote-edit2/lib/model/host.coffee:17:19)
    at new FtpHost (/home/yzhao/.atom/packages/remote-edit2/lib/model/ftp-host.coffee:32:7)
    at Object.module.exports.newHostFtp (/home/yzhao/.atom/packages/remote-edit2/lib/main.coffee:116:16)
    at atom-workspace.<anonymous> (/home/yzhao/.atom/packages/remote-edit2/lib/main.coffee:95:73)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1104:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -0:00.1.0 remote-edit:new-host-ftp (atom-pane.pane.active)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.8.1 (active)
remote-edit2, v3.0.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by boubouhkarim** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.9
**System**: "Arch Linux"
**Thrown From**: 'remote-edit' package, vundefined


### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:575

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:575:11)
    at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:184:20)
    at new InterProcessDataWatcher (/home/karim/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:17:10)
    at Object.module.exports.getOrCreateIpdw (/home/karim/.atom/packages/remote-edit2/lib/main.coffee:148:19)
    at Object.module.exports.browse (/home/karim/.atom/packages/remote-edit2/lib/main.coffee:122:27)
    at atom-workspace.<anonymous> (/home/karim/.atom/packages/remote-edit2/lib/main.coffee:93:67)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -6:44.7.0 core:paste (atom-text-editor.editor.is-focused)
     -6:38 editor:delete-line (atom-text-editor.editor.is-focused)
     -6:35.9.0 core:undo (atom-text-editor.editor.is-focused)
  3x -6:29.3.0 editor:delete-line (atom-text-editor.editor.is-focused)
  2x -6:26.8.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -6:26.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:23.3.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -6:22.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:17.7.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -6:17.3.0 core:save (atom-text-editor.editor.is-focused)
     -6:12.1.0 core:copy (atom-text-editor.editor.is-focused)
  4x -5:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:45.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:43.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 remote-edit:browse (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-autocomplete-php",
      "activate-power-mode",
      "linter-python-pep8",
      "terminal-plus",
      "python-debugger",
      "python-tools",
      "linter-pep8"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "remote-edit": {
    "clearFileList": true,
    "filterHostsUsing": {
      "alias": true
    },
    "foldersOnTop": true,
    "rememberLastOpenDirectory": true,
    "showHiddenFiles": true,
    "storePasswordsUsingKeytar": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.8.1 (inactive)
atom-autocomplete-php, v0.18.9 (inactive)
atom-beautify, v0.29.11 (active)
atom-jinja2, v0.5.0 (active)
atom-material-syntax, v0.4.6 (active)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.5 (active)
atom-minify, v0.7.5 (active)
atom-terminal, v0.8.0 (inactive)
autocomplete-python, v1.8.6 (active)
cake-syntax, v0.5.3 (inactive)
css-snippets, v1.0.0 (active)
emmet, v2.4.3 (active)
fast-eslint, v3.0.0 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.16 (active)
linter-js-yaml, v1.2.5 (active)
linter-json-lint, v0.1.1 (active)
linter-python, v3.0.5 (active)
pigments, v0.33.1 (active)
python-debugger, v0.1.0 (inactive)
python-tools, v0.6.8 (inactive)
remote-edit2, v3.0.0 (active)
Remote-FTP, v0.8.8 (active)
seti-icons, v1.3.2 (active)
seti-ui, v1.3.2 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
terminal-plus, v0.14.5 (inactive)
vue-autocomplete, v0.1.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Nollikino** [comment]
You are all using the package:
remote-edit2

That is a fork if THIS package:
remote-edit

There seems to be some namespace issues with that fork, and I suggest that you open up your tickets on their fork.

It seems to me like the package "remote-edit2" is still using the path for "remote-edit" for some files, and as such cannot find some of the config-files/Variables. But as that is an issue with another fork, there is nothing we can do here.

**Comment by boubouhkarim** [comment]
Yes, for remote-edit, when i try to install it, i end up with this issue :

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.9
**System**: "Arch Linux"
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24


### Stack Trace

Failed to load the remote-edit package

```
At Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'

Error: Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/karim/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:9:17)
    at Object.<anonymous> (/home/karim/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/karim/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (/home/karim/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:536:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

### Commands

```
     -0:57.6.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-autocomplete-php",
      "activate-power-mode",
      "linter-python-pep8",
      "terminal-plus",
      "python-debugger",
      "python-tools",
      "linter-pep8"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "remote-edit": {
    "clearFileList": true,
    "filterHostsUsing": {
      "alias": true
    },
    "foldersOnTop": true,
    "rememberLastOpenDirectory": true,
    "showHiddenFiles": true,
    "storePasswordsUsingKeytar": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.8.1 (inactive)
atom-autocomplete-php, v0.18.9 (inactive)
atom-beautify, v0.29.11 (active)
atom-jinja2, v0.5.0 (active)
atom-material-syntax, v0.4.6 (active)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.5 (active)
atom-minify, v0.7.5 (active)
atom-terminal, v0.8.0 (inactive)
autocomplete-python, v1.8.6 (active)
cake-syntax, v0.5.3 (inactive)
css-snippets, v1.0.0 (active)
emmet, v2.4.3 (active)
fast-eslint, v3.0.0 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.16 (active)
linter-js-yaml, v1.2.5 (active)
linter-json-lint, v0.1.1 (active)
linter-python, v3.0.5 (active)
pigments, v0.33.1 (active)
python-debugger, v0.1.0 (inactive)
python-tools, v0.6.8 (inactive)
remote-edit, v1.8.24 (inactive)
Remote-FTP, v0.8.8 (active)
seti-icons, v1.3.2 (active)
seti-ui, v1.3.2 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
terminal-plus, v0.14.5 (inactive)
vue-autocomplete, v0.1.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (active)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Nollikino** [comment]
@boubouhkarim There should have been a link to an active Issue regarding that when that error was thrown, like #188, #189 or #190.

All of these issues is because of a command was deprecated since Atom version 1.9.x forwards. You can see the fix for the problem at the pull request: #187

**Comment by boubouhkarim** [comment]
Thank you! @Nollikino removing the line referenced in #187  fixed the problem.
why isn't merged yet with the repo !

**Comment by Nollikino** [comment]
@boubouhkarim The reason it isn't merged yet is most probably because the "owner" of this project has been inactive on github for a couple of months. But, because of the "easy fix" that is in that Pull Request, there hasn't been a big push to populate the other Repository.
