### ISSUE TITLE
Uncaught TypeError: result.sort is not a function

### ISSUE THREAD

**Issue by Captnwalker1** [sveale/remote-edit#197]
[Enter steps to reproduce below:]

1. setup sftp host
2. browse hosts
3. click host
4. connection successful
5. error Uncaught TypeError: result.sort is not a function

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24

### Stack Trace

Uncaught TypeError: result.sort is not a function

```
At /C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:276

TypeError: result.sort is not a function
    at file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:152:34
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:486:20
    at nextTask (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:5008:33)
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:5015:17
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:339:31
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:847:20
    at file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:145:95
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:486:20
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:3306:17
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:952:25
    at iteratorCallback (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:995:17)
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:847:20
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:3296:21
    at RemoteFile.module.exports.RemoteFile.isHidden (file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/remote-file.coffee:15:7)
    at file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:145:61
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:3294:13
    at eachOfArrayLike (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1002:13)
    at eachOf (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1052:9)
    at _filter (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:3293:9)
    at Object.<anonymous> (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1057:20)
    at async.waterfall._this.emitter.emit.message (file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:145:19)
    at nextTask (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:5021:18)
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:5015:17
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:339:31
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:847:20
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:486:20
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1074:13
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:952:25
    at iteratorCallback (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:997:17)
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:847:20
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1071:17
    at file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:139:49
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1069:13
    at eachOfArrayLike (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1002:13)
    at eachOf (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1052:9)
    at _asyncMap (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1067:9)
    at Object.map (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:1057:20)
    at file:///C:/Users/Username/.atom/packages/remote-edit/lib/model/sftp-host.coffee:139:17
    at nextTask (C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:5021:18)
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:5015:17
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:339:31
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\async\dist\async.js:847:20
    at C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2-streams\lib\sftp.js:1503:13
    at SFTPStream._transform (C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2-streams\lib\sftp.js:382:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2-streams\lib\sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SFTPStream.Writable.write (_stream_writable.js:215:11)
    at Channel.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Channel.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Channel.Readable.push (_stream_readable.js:111:10)
    at SSH2Stream.<anonymous> (C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2\lib\Channel.js:146:15)
    at emitOne (events.js:90:13)
    at SSH2Stream.emit (events.js:182:7)
    at parsePacket (C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2-streams\lib\ssh.js:3163:10)
    at SSH2Stream._transform (C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2-streams\lib\ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\Username\.atom\packages\remote-edit\node_modules\ssh2-streams\lib\ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at SSH2Stream.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

### Commands

```
  2x -0:25.7.0 remote-edit:browse (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-sync"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.19 (active)
pigments, v0.34.0 (active)
project-manager, v2.9.7 (active)
remote-edit, v1.8.24 (active)
remote-sync, v4.1.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by palominogallo** [comment]
On settings, activate the option to see hidden files. (not best solution, but works).

The problem seems to come from the way of filtering the hidden files, maybe somebody knows more about `async.filter`

**Comment by noullove** [comment]
package.json

  "dependencies": {
    "async": ">=0.9.0",

     replace with 

    "async": "<2.0.0", 

and cmd window "npm install" inside directory remote-edit package.
