### ISSUE TITLE
Uncaught TypeError: objects.push is not a function

### ISSUE THREAD

**Issue by muuvmuuv** [sveale/remote-edit#200]
[Enter steps to reproduce below:]

1. Add a remote ftp
2. List all
3. Try to connect
4. Says connected and threw this error:

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24

### Stack Trace

Uncaught TypeError: objects.push is not a function

```
At /Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:112

TypeError: objects.push is not a function
    at async.waterfall._this.emitter.emit.message (/Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:112:19)
    at nextTask (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:5021:18)
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:5015:17
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:339:31
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:110:85
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:486:20
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:3306:17
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:995:17)
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:3296:21
    at /Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:110:54
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:3294:13
    at eachOfArrayLike (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1002:13)
    at eachOf (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1052:9)
    at _filter (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:3293:9)
    at Object.<anonymous> (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1057:20)
    at /Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:110:17
    at nextTask (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:5021:18)
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:5015:17
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:339:31
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:486:20
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1074:13
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:997:17)
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1071:17
    at /Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:108:49
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1069:13
    at eachOfArrayLike (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1002:13)
    at eachOf (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1052:9)
    at _asyncMap (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1067:9)
    at Object.map (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:1057:20)
    at /Users/marvinheilemann/.atom/packages/remote-edit/lib/model/ftp-host.coffee:108:17
    at nextTask (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:5021:18)
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:5015:17
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:339:31
    at /Users/marvinheilemann/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at final (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/Users/marvinheilemann/.atom/packages/remote-edit/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:47.5.0 remote-edit:new-host-ftp (atom-pane.pane.active)
     -0:40.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:34.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:29.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -0:29.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:11.3.0 remote-edit:browse (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "tool-bar",
      "angularjs-helper",
      "remote-edit",
      "atom-commander"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (active)
angularjs-helper, v0.10.2 (inactive)
autocomplete-angular-material, v0.4.0 (active)
block-comment, v0.4.3 (inactive)
color-picker, v2.2.2 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
git-plus, v5.17.1 (inactive)
git-status, v0.3.4 (inactive)
language-mongodb, v0.3.1 (active)
linter, v1.11.16 (active)
minimap, v4.25.0 (active)
minimap-pigments, v0.2.1 (active)
ninja-syntax, v0.0.0 (inactive)
php-twig, v4.0.0 (active)
pigments, v0.34.0 (active)
project-manager, v3.2.3 (active)
remote-edit, v1.8.24 (active)
Remote-FTP, v0.8.9 (active)
sync-settings, v0.7.2 (active)
tabs-to-spaces, v1.0.2 (active)
tool-bar, v1.0.1 (active)
tool-bar-almighty, v0.7.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by alhoseany** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24


### Stack Trace

Uncaught TypeError: objects.push is not a function

```
At /Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:112

TypeError: objects.push is not a function
    at async.waterfall._this.emitter.emit.message (/Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:112:19)
    at nextTask (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:5021:18)
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:5015:17
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:339:31
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:110:85
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:486:20
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:3306:17
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:995:17)
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:3296:21
    at /Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:110:54
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:3294:13
    at eachOfArrayLike (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1002:13)
    at eachOf (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1052:9)
    at _filter (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:3293:9)
    at Object.<anonymous> (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1057:20)
    at /Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:110:17
    at nextTask (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:5021:18)
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:5015:17
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:339:31
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:486:20
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1074:13
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:997:17)
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1071:17
    at /Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:108:49
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1069:13
    at eachOfArrayLike (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1002:13)
    at eachOf (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1052:9)
    at _asyncMap (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1067:9)
    at Object.map (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:1057:20)
    at /Users/alhoseany/.atom/packages/remote-edit/lib/model/ftp-host.coffee:108:17
    at nextTask (/Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:5021:18)
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:5015:17
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:339:31
    at /Users/alhoseany/.atom/packages/remote-edit/node_modules/async/dist/async.js:847:20
    at final (/Users/alhoseany/.atom/packages/remote-edit/node_modules/ftp/lib/connection.js:476:11)
    at Socket.ondone (/Users/alhoseany/.atom/packages/remote-edit/node_modules/ftp/lib/connection.js:451:7)
    at Socket.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:14.8.0 remote-edit:show-open-files (atom-text-editor.editor.mini.is-focused)
     -1:05.4.0 remote-edit:new-host-ftp (atom-text-editor.editor.mini.is-focused)
     -0:40.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
 11x -0:39.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:26.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:04.6.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.24 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by normic** [comment]
I guess this project is dead, just fixed issue #189 which is barely old and now I stumbled about this one which is also nearly a old and no comment from the author.

**Comment by ivan82** [comment]
To resolve this change async dependency version.
Open file: ~/.atom/packages/remote-edit/package.json
change line 47: 
`"async": ">=0.9.0"`
to
`"async": "<2.0.0"`

in the  ~/.atom/packages/remote-edit/ folder run the `npm install` command
