### ISSUE TITLE
only problems with all Atoms... I have tested Atom old, Atom New and now Atom Beta.

### ISSUE THREAD

**Issue by burhan-kun** [sveale/remote-edit#207]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0-beta2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24

### Stack Trace

Failed to load the remote-edit package

```
At Cannot find module '/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer'

Error: Cannot find module '/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/display-buffer'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Burhan/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:9:17)
    at Object.<anonymous> (/Users/Burhan/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module._compile (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Burhan/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (/Users/Burhan/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module._compile (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/package.js:760:27)
    at /private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/package.js:121:28
    at Package.module.exports.Package.measure (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/package.js:94:15)
    at Package.module.exports.Package.load (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/package.js:108:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:466:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:546:30)
    at /private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:299:11)
    at /private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:312:11
    at Socket.<anonymous> (/private/var/folders/d9/n525t8rn75vf981rh5wjm2y00000gn/T/AppTranslocation/8D3ADC99-4B7F-4672-857A-B223440C8330/d/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

### Commands

```
     -5:57.8.0 remote-ftp:toggle (input.hidden-input)
     -5:46.2.0 remote-ftp:disconnect (input.hidden-input)
     -5:40.3.0 tree-view:toggle-focus (input.hidden-input)
     -5:39.3.0 editor:consolidate-selections (input.hidden-input)
     -5:39.3.0 core:cancel (input.hidden-input)
     -5:32 editor:toggle-soft-wrap (input.hidden-input)
     -5:22.9.0 command-palette:toggle (input.hidden-input)
     -5:15.3.0 window:run-package-specs (input.hidden-input)
     -4:42.7.0 window:focus-pane-on-left (input.hidden-input)
     -4:08.3.0 settings-view:install-packages-and-themes (input.hidden-input)
     -3:38.4.0 core:confirm (input.hidden-input)
     -1:04.2.0 settings-view:install-packages-and-themes (input.hidden-input)
```

### Config

```json
{
  "core": {
    "fileEncoding": "iso88591",
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.24 (inactive)
remote-sync, v4.1.5 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

Since Yesterday i can not install a anything FTP Tool.... I have only problems... Please help me

**Comment by borekon** [comment]
The same happens to me. Fresh Ubuntu and Atom install.
