### ISSUE TITLE
Uncaught TypeError: Cannot read property 'alias' of undefined

### ISSUE THREAD

**Issue by benyanke** [sveale/remote-edit#208]
1) Dropdown packages menu 
2) Remote Edit
3) Add New SFTP host

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [remote-edit2](https://github.com/duxet/remote-edit2) package, v3.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'alias' of undefined

```
At /home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/model/host.coffee:34

TypeError: Cannot read property 'alias' of undefined
    at SftpHost.module.exports.Host.getSearchKey (/home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/model/host.coffee:34:63)
    at /home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/model/host.coffee:18:9
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:141:21)
    at SftpHost.Host (/home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/model/host.coffee:17:19)
    at new SftpHost (/home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/model/sftp-host.coffee:32:7)
    at Object.newHostSftp (/home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/main.coffee:109:16)
    at atom-workspace.<anonymous> (/home/benyanke/NextCloud/config-sync-files/dotfiles/dot.atom/packages/remote-edit2/lib/main.coffee:94:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -1:20.5.0 remote-edit:browse (div.package-detail.panels-item)
     -0:36.2.0 fuzzy-finder:toggle-git-status-finder (div.package-detail.panels-item)
     -0:34 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:32.9.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -0:31.9.0 application:open-folder (atom-text-editor.editor.is-focused)
     -0:26.9.0 find-and-replace:use-selection-as-find-pattern (atom-text-editor.editor.is-focused)
     -0:25.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:25.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:22.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 remote-edit:new-host-sftp (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  },
  "remote-edit2": {
    "filterHostsUsing": {
      "alias": true
    }
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-beautify, v0.29.13 (active)
git-plus, v5.29.0 (active)
remote-atom, v1.3.10 (active)
remote-edit2, v3.0.0 (active)
select-rectangle, v1.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by urban-1** [comment]
Hi @benyanke 

I fixed this problem [in my fork](https://github.com/urban-1/remote-edit2/commit/f64da8e50492a73c5129f94459dcb84ac2753b1e) by renaming all configuration references to `"remote-edit2. ..."`

Also note that `remote-edit2` is maintained by @duxet (I think...) at https://github.com/duxet/remote-edit2  - I made a PR today. 

You can try my fork and see if it works for you.

Cheers,
Andreas

**Comment by benyanke** [comment]
I ended up finding another plugin which better suited my needs, but if I ever need to come back to remote-edit, I'll certainly give it a shot!

https://github.com/amoussard/sftp-deployment

This plugin allows automatic upload on save, which is exactly what I needed.
