### ISSUE TITLE
Failed to load the remote-edit package

### ISSUE THREAD

**Issue by bhvreddy** [sveale/remote-edit#212]
Cannot find module 'C:\Users\v\AppData\Local\atom\app-1.13.1\resources\app.asar\src\display-buffer'

**Comment by ssarangi** [comment]
+1 upvote

**Comment by Shark4109** [comment]
+1
Linux version: 
`Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'`

**Comment by kaufmann42** [comment]
any solutions found to this?

Here's my stack-trace:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.4
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.24


### Stack Trace

Failed to load the remote-edit package

```
At Cannot find module '/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/display-buffer'

Error: Cannot find module '/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/display-buffer'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/johnkaufmann/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:9:17)
  at Object.<anonymous> (/Users/johnkaufmann/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
  at Module._compile (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .coffee] (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/johnkaufmann/.atom/packages/remote-edit/lib/main.coffee:3:20)
  at Object.<anonymous> (/Users/johnkaufmann/.atom/packages/remote-edit/lib/main.coffee:1:1)
  at Module._compile (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
  at Object.value [as .coffee] (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:766:27)
  at /Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:121:28
  at Package.module.exports.Package.measure (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
  at Package.module.exports.Package.load (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:108:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
  at /Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
  at /Users/johnkaufmann/Desktop/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:811:28

```

### Commands

```
     -0:00.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (inactive)
atom-beautify, v0.29.17 (inactive)
atom-easy-jsdoc, v4.9.0 (inactive)
autocomplete-plus, v2.34.2 (inactive)
autocomplete-python, v1.8.34 (inactive)
color-picker, v2.2.5 (inactive)
editorconfig, v2.2.0 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v2.0.13 (inactive)
kite, v0.7.6 (inactive)
linter, v1.11.21 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.26.8 (inactive)
python-tools, v0.6.9 (inactive)
remote-edit, v1.8.24 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.34.2 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by kaufmann42** [comment]
duplicated issue:

https://github.com/sveale/remote-edit/issues/199

**Comment by jessejamesrichard** [comment]
+1

**Comment by mehdiraized** [comment]
+1

**Comment by takotuesday** [comment]
+1

**Comment by kalavrouziotis** [comment]
+1

**Comment by kevinak941** [comment]
+1

**Comment by SachithS** [comment]
+1

**Comment by isikfsc** [comment]
+1

**Comment by dpetrov** [comment]
+1

**Comment by Venegrad** [comment]
+1

**Comment by benkahandevelopment** [comment]
+1

**Comment by smacc364** [comment]
+1

**Comment by ollez** [comment]
+1

**Comment by patskan** [comment]
+1

**Comment by jpazzini** [comment]
+1

**Comment by mpergament** [comment]
+1

**Comment by mrhannachi** [comment]
+1 on Atom 1.22.1
Cannot find module '/usr/share/atom/resources/app.asar/src/display-buffer'
**EDIT: not reproduced after updating remote-edit package.**

**Comment by ghost** [comment]
+1

**Comment by Olmer1st** [comment]
Atom 1.25.0
+1

**Comment by ghost** [comment]
+1

**Comment by robertandrews** [comment]
+1

**Comment by atastycookie** [comment]
+2

**Comment by so77id** [comment]
+1

**Comment by Kaspichhh** [comment]
+1

**Comment by atastycookie** [comment]
+!

**Comment by gapanda** [comment]
+1

**Comment by jpcamba** [comment]
+1

**Comment by gaddman** [comment]
For all those giving a +1 comment, you can just hit the thumbs up button on the first comment to show your enthusiasm - and avoid spamming other bug followers. Keep the comments for information that will help the developers identify/fix the bug.
In saying that, the last commit was over a year ago, and the author hasn't committed to any projects in 9 months - so I wouldn't hold a lot of hope it will be fixed. Either follow the instructions in https://github.com/sveale/remote-edit/issues/199#issuecomment-249667891 or look for a new plugin.

**Comment by dubus-b** [comment]
+1

**Comment by uussmmoonn** [comment]
+1

**Comment by li13738051517** [comment]
+1

**Comment by WhiteInk404** [comment]
+1

**Comment by shishov** [comment]
+1

**Comment by obito02** [comment]
+1

**Comment by niccw** [comment]
+1

**Comment by smonolo** [comment]
+1

**Comment by soeric** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0


### Stack Trace

Failed to load the remote-edit package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/remote-edit/lib/main.coffee:3:20)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:819:20)
```

### Commands

```
```

### Non-Core Packages

```
language-lua 0.9.11 
markdown-preview-plus 3.2.2 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
pretty-json 2.0.0 
remote-edit 1.9.0 
```

**Comment by iszihan** [comment]
+1

**Comment by petertwise** [comment]
remote-edit appears to be abandoned. Try out [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) instead.

**Comment by Tromineo** [comment]
1
