### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Pushpinder2751** [sveale/remote-edit#225]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:731

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Proxy.fs.readFileSync (fs.js:534:19)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at SftpHost.module.exports.SftpHost.getPrivateKey (/packages/remote-edit/lib/model/sftp-host.coffee:69:17)
    at SftpHost.module.exports.SftpHost.getConnectionStringUsingKey (/packages/remote-edit/lib/model/sftp-host.coffee:53:74)
    at SftpHost.module.exports.SftpHost.getConnectionString (/packages/remote-edit/lib/model/sftp-host.coffee:90:26)
    at /packages/remote-edit/lib/model/sftp-host.coffee:124:32
    at fn (/packages/remote-edit/node_modules/async/lib/async.js:746:34)
    at /packages/remote-edit/node_modules/async/lib/async.js:1213:16
    at /packages/remote-edit/node_modules/async/lib/async.js:166:37
    at /packages/remote-edit/node_modules/async/lib/async.js:706:43
    at /packages/remote-edit/node_modules/async/lib/async.js:167:37
    at /packages/remote-edit/node_modules/async/lib/async.js:1209:30
    at /packages/remote-edit/lib/model/sftp-host.coffee:107:17
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

### Commands

```
     -4:52.8.0 remote-edit:new-host-sftp (div.package-detail.panels-item)
     -4:39.3.0 core:paste (input.hidden-input)
     -4:15.7.0 remote-edit:browse (div.package-detail.panels-item)
     -4:14.1.0 core:confirm (input.hidden-input)
 16x -3:37.7.0 core:backspace (input.hidden-input)
     -3:28.1.0 remote-edit:browse (div.package-detail.panels-item)
     -3:01.4.0 core:confirm (input.hidden-input)
     -2:17.4.0 remote-edit:browse (div.package-detail.panels-item)
     -2:05.1.0 remote-edit:new-host-sftp (div.package-detail.panels-item)
     -1:57.7.0 core:paste (input.hidden-input)
  6x -1:46.1.0 core:backspace (input.hidden-input)
     -0:27.7.0 core:paste (input.hidden-input)
     -0:12.3.0 remote-edit:browse (div.package-detail.panels-item)
     -0:09.5.0 core:move-down (input.hidden-input)
     -0:09.0 core:move-up (input.hidden-input)
     -0:06.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-gooey-syntax 1.0.0 
clipboard-plus 0.5.1 
color-picker 2.2.5 
expose 0.14.0 
git-control 0.9.0 
git-time-machine 1.5.9 
idiomatic-dark-syntax 0.1.3 
merge-conflicts 1.4.4 
minimap 4.27.1 
open-recent 5.0.0 
remote-edit 1.9.0 
sync-settings 0.8.1 
```

**Comment by alexfromapex** [comment]
I had the same issue, while simply trying to connect.

```
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at tryReadSync (fs.js:457:20)
    at Proxy.fs.readFileSync (fs.js:494:19)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at SftpHost.module.exports.SftpHost.getPrivateKey (/Users/alex/.atom/packages/remote-edit/lib/model/sftp-host.coffee:69:17)
    at SftpHost.module.exports.SftpHost.getConnectionStringUsingKey (/Users/alex/.atom/packages/remote-edit/lib/model/sftp-host.coffee:55:74)
    at SftpHost.module.exports.SftpHost.getConnectionString (/Users/alex/.atom/packages/remote-edit/lib/model/sftp-host.coffee:90:26)
    at /Users/alex/.atom/packages/remote-edit/lib/model/sftp-host.coffee:124:32
    at fn (/Users/alex/.atom/packages/git-plus/node_modules/async/lib/async.js:746:34)
    at /Users/alex/.atom/packages/git-plus/node_modules/async/lib/async.js:1213:16
    at /Users/alex/.atom/packages/git-plus/node_modules/async/lib/async.js:166:37
    at /Users/alex/.atom/packages/git-plus/node_modules/async/lib/async.js:706:43
    at /Users/alex/.atom/packages/git-plus/node_modules/async/lib/async.js:167:37
    at /Users/alex/.atom/packages/git-plus/node_modules/async/lib/async.js:1209:30
    at /Users/alex/.atom/packages/remote-edit/lib/model/sftp-host.coffee:107:17
    at FSReqWrap.cb [as oncomplete] (fs.js:240:19)
```
