### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by amuehlem** [sveale/remote-edit#232]
[Enter steps to reproduce:]

1. Browse Host
2. Select Host

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:238

TypeError: path must be a string or Buffer
    at fs.exists (fs.js:238:11)
    at Object.fs.exists (ELECTRON_ASAR.js:364:16)
    at /packages/remote-edit/lib/model/sftp-host.coffee:105:16
    at fn (/packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:716:34)
    at /packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:1169:16
    at /packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:661:43
    at Object.async.waterfall (/packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:665:44)
    at SftpHost.module.exports.SftpHost.connect (/packages/remote-edit/lib/model/sftp-host.coffee:102:13)
    at /packages/remote-edit/lib/view/files-view.coffee:49:19
    at fn (/packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:716:34)
    at /packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:1169:16
    at /packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:661:43
    at /packages/atom-beautify/node_modules/universal-analytics/node_modules/async/lib/async.js:1162:34)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:14.9.0 remote-edit:browse (input.hidden-input)
```

### Non-Core Packages

```
ansible-vault 0.6.7 
atom-beautify 0.30.5 
atom-gpg 0.5.0 
git-control 0.9.0 
git-plus 7.9.3 
hashrocket 0.4.10 
remote-atom 1.3.11 
remote-edit 1.9.0 
shell-it 0.2.1 
sort-lines 0.15.0 
split-diff 1.5.1 
xml-tools 0.2.1 
```

**Comment by COOLIRON2311** [comment]
I have same issue

**Comment by Bhlowe** [comment]
Same, but different line number.. this is on windows. 
fs.js:549
Get the error when I try to browser or create a new FTP or SFTP connection. 
FYI, selecting toggle file view shows FTP:unknown Folder:unknown. But I have two connections open. 
Was also seeing another error,  https://github.com/sveale/remote-edit/issues/169
My other existing ssh directories are working.. just can't add new ones.
Latest updates. Can send windows stack--slightly different than above.
