### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by ijash** [sveale/remote-edit#243]
> ### current fix:
>  check post by @eth0izzle 

[Enter steps to reproduce:]

1. install remote-edit and restart atom

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Linux Mint 18.03
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0

### Stack Trace

Failed to load the remote-edit package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/remote-edit/lib/main.coffee:3:20)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at measure (/usr/share/atom/resources/app/src/package.js:143:22)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:689:23)
```

### Commands

```
```

### Non-Core Packages

```
remote-edit 1.9.0 
```

**Comment by miroslavrussev** [comment]
I can confirm that the issue is present on Windows as well:

[Enter steps to reproduce:]

1. install remote-edit and restart atom

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0


### Stack Trace

Failed to load the remote-edit package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/remote-edit/lib/main.coffee:3:20)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.25.1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.25.1/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:531:20)
    at Config.transact (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:815:20)
```

### Commands

```
```

### Non-Core Packages

```
remote-edit 1.9.0 
```

**Comment by FhlostonParadise** [comment]
[Enter steps to reproduce:]

install remote-edit and restart atom
Atom: 1.25.1 x64  
Electron: 1.7.11
OS: Microsoft Windows 10 Professional
Thrown From: remote-edit package 1.9.0



Confirmed as exactly the same as above.

**Comment by yelled1** [comment]
confirming error on Elementary OS 0.4 (Ubuntu 16.04)
Atom 1.26.1 x64

**Comment by fspiga** [comment]
Same problem on OSX 10.13.5 Beta with Atom 1.26.1

**Comment by rjimeno** [comment]
Same for me! PLEASE SUGGEST A WORKAROUND!

[Enter steps to reproduce:]

install remote-edit and restart atom
Atom: 1.26.1 x64
Electron: 1.7.11
OS: macOs High Sierra version 10.13.2 (OSX)
Thrown From: remote-edit package 1.9.0

Confirmed the same as above.

**Comment by coxa** [comment]
Confirmed

`
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.<anonymous> (/Users/m.sahnouski/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at Object.<anonymous> (/Users/m.sahnouski/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Object.<anonymous> (/Users/m.sahnouski/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/m.sahnouski/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (/Users/m.sahnouski/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Object.<anonymous> (/Users/m.sahnouski/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:819:20)
`

MacOS High Sierra
Atom 1.27.0
remote-edit 1.9.0

**Comment by eth0izzle** [comment]
Fix (at least for me on Windows 10):

1. Open ~\\.atom\packages\remote-edit\lib\model\remote-edit-editor.coffee
2. Change line `resourcePath = atom.config.resourcePath` to `resourcePath = atom.getLoadSettings().resourcePath`

**Comment by edautz** [comment]
Followed the solution of @eth0izzle.

Worked for me on windows7.

Thanx

**Comment by neilcatalan** [comment]
Followed solution of @eth0izzle but I encountered another issue I cannot see any connection when browsing and even I save a connection it doesn't show up when browsing.

I'm on a Windows 10, Atom 1.27.1, and remote-edit 1.9.0

**Comment by ijash** [comment]
**I Confirm this is the current fix** 
I have followed the instruction by @eth0izzle  and the error message disappear on **Linux Mint 18.03**..

how did you find the fix? at least tell us how it works (or you did) if you please.

**Comment by cromefire** [comment]
Confirmed on Ubuntu 18.04, Atom 1.27.2 x64, fix seems to work

**Comment by ETRick** [comment]
Followed solution of @eth0izzle and it works for me on windows10, atom 1.27.2

**Comment by Pandaoc-io** [comment]
Have the same issue on Windows 10 with Atom 1.28.0 x64 and remote-edit 1.9.0
Solved by the solution given by @eth0izzle. Thank for the fix

**Comment by Pyragon** [comment]
Followed solution by @eth0izzle, package now loads up, however not able to add any hosts, or see any hosts when browsing. No errors are present.

**Comment by aasimali141290** [comment]
followed @eth0izzle  solution it is working for MacOS

**Comment by cbailes** [comment]
Confirmed on Ubuntu 18.04.1 x64, Atom 1.28.2 x64, remote-edit 1.9.0.

Solution by @eth0izzle is working.
