### ISSUE TITLE
Failed to load the remote-edit package

### ISSUE THREAD

**Issue by ZohrehGorji** [sveale/remote-edit#247]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0

### Stack Trace

Failed to load the remote-edit package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1186:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/remote-edit/lib/main.coffee:3:20)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:1:639512)
    at Package.requireMainModule (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:2951243)
    at measure (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:2937954)
    at Package.measure (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:2936786)
    at Package.load (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:2937527)
    at PackageManager.loadAvailablePackage (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:381285)
    at config.transact (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:379708)
    at Config.transact (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:332241)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-material-ui 2.1.3 
atom-prettify 0.1.3 
atomic-chrome 0.3.3 
auto-update-packages 1.0.1 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 2.0.0 
color-picker 2.3.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.30 
git-plus 8.6.1 
git-time-machine 2.1.0 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
intentions 1.1.5 
language-liquid 0.7.0 
linter 2.3.0 
linter-eslint 8.5.2 
linter-rubocop 2.2.4 
linter-scss-lint 3.2.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pdf-view 0.71.0 
pigments 0.40.2 
project-manager 3.3.6 
remote-edit 1.9.0 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
terminal-plus 0.14.5 
vim-mode 0.66.0 
web-view 3.0.0 
```

**Comment by ChristianP93** [comment]
+1

**Comment by jsett** [comment]
same here.

**Comment by Casper-O** [comment]
This module have not been updated for two years - read this issue with suggestions https://github.com/sveale/remote-edit/issues/246

**Comment by Mikehunt1** [comment]
me too

**Comment by YoussF** [comment]
+1

**Comment by Zoher15** [comment]
+1

**Comment by prii-yanka** [comment]
+1

**Comment by webstarlet** [comment]
+1

**Comment by wildwho** [comment]
+1

**Comment by joaoescribano** [comment]
+1

**Comment by YamelYAT** [comment]
+1

**Comment by dylan8911** [comment]
+1

**Comment by luisarojas** [comment]
+1

**Comment by daveroseman** [comment]
+1

**Comment by jameshahn2** [comment]
Same...

**Comment by tina80lvl** [comment]
Same, so where's the solution🤔

**Comment by kucerakk** [comment]
+1

**Comment by layagollapudi** [comment]
same

**Comment by jacklynch00** [comment]
+1

**Comment by zlang19** [comment]
+1

**Comment by mf-1** [comment]
+1

**Comment by jkumar-roambee** [comment]
+1

**Comment by Oceanwall** [comment]
+1

**Comment by XHXHXHX** [comment]
+1

**Comment by TimHe95** [comment]
+1

**Comment by amiyata** [comment]
++

**Comment by zinmin-edge** [comment]
same issue occurred. anyone solved it yet?

**Comment by xgme** [comment]
This happens to me from time to time. Each time it happens, I try restarting Atom, try opening/closing the project again and again. Eventually the problem gets fixed after 5-10 minutes. Not sure what's causing the issue and what's solving it.

**Comment by DamianStanczykDSDesigner** [comment]
same ...

**Comment by egor-doudkin-mpf** [comment]
same

**Comment by mpaul138** [comment]
same

**Comment by ugultopu** [comment]
👍

**Comment by manicmarvin** [comment]
same

**Comment by maciejkola** [comment]
Just like Casper-O wrote, use **ftp-remote-edit** (works over SSH):
https://atom.io/packages/ftp-remote-edit

**Comment by johnla** [comment]
any fix? +1

**Comment by LebsterFace** [comment]
++

**Comment by M-Scholli** [comment]
same
