### ISSUE TITLE
Failed to load the remote-edit package

### ISSUE THREAD

**Issue by NanaKay007** [sveale/remote-edit#251]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0

### Stack Trace

Failed to load the remote-edit package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/remote-edit/lib/main.coffee:3:20)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:1:692867)
    at Package.requireMainModule (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3223932)
    at measure (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3210472)
    at Package.measure (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3209304)
    at Package.load (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:3210045)
    at PackageManager.loadAvailablePackage (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:381026)
    at PackageManager.loadPackage (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:379754)
    at PackageManager.activatePackage (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:382326)
    at /private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:941017
    at r (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:11:935623)
    at n (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1124536)
    at ChildProcess.o.process.on.e (/private/var/folders/c9/gf0ncpfs1rdfcrdksqr9_g_00000gp/T/AppTranslocation/430FD18A-2057-4A34-B569-7A8A1B89F652/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1124742)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -3:28.1.0 settings-view:open (atom-pane.pane.active)
```

### Non-Core Packages

```
remote-edit 1.9.0 
```

**Comment by Shesoff** [comment]
I have same trouble

**Comment by phunter33** [comment]
remote-edit-ni is the one you should now use.

**Comment by Shesoff** [comment]
> remote-edit-ni is the one you should now use.

Unfortunetly, remote-edit-ni don't support ssh keys authorisation :-(

**Comment by facundobianco** [comment]
Same issue on Mac OSX.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2 (Catalina)
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:16:55)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:258:4)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:262:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .coffee] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (<embedded>:11:146745)
    at /packages/remote-edit/lib/main.coffee:6:22)
    at /packages/remote-edit/lib/main.coffee:274:4)
    at /packages/remote-edit/lib/main.coffee:278:3)
    at Module.get_Module._compile (<embedded>:11:147429)
    at Object.value [as .coffee] (<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (<embedded>:1:695134)
    at Package.requireMainModule (<embedded>:11:3233575)
    at measure (<embedded>:11:3220115)
    at Package.measure (<embedded>:11:3218947)
    at Package.load (<embedded>:11:3219688)
    at PackageManager.loadAvailablePackage (<embedded>:11:381026)
    at config.transact (<embedded>:11:379449)
    at Config.transact (<embedded>:11:331514)
    at PackageManager.loadPackages (<embedded>:11:379387)
    at t.loadState.then (<embedded>:1:715745)
```

**Comment by reedx8** [comment]
Im experiencing the same issue on macOS Catalina

**Comment by db369** [comment]
It's an issue on Linux Mint 19.3 as well. FYI.

**Comment by mkumar118** [comment]
The same experience on Windows 10

I've just freshly installed Atom to be able to use this package :(

`The "path" argument must be of type string. Received type undefined
Hide Stack Trace
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.resolve (path.js:136:9)
    at Object.<anonymous> (file:///C:/Users/mkumar/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at Object.<anonymous> (file:///C:/Users/mkumar/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/mkumar/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .coffee] (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/mkumar/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/mkumar/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (file:///C:/Users/mkumar/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/mkumar/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .coffee] (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/mkumar/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3310163)
    at C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3296703
    at Package.measure (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3295535)
    at Package.load (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3296276)
    at PackageManager.loadAvailablePackage (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:381312)
    at PackageManager.loadPackage (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:380040)
    at PackageManager.activatePackage (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:382612)
    at C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:926575
    at r (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:921181)
    at n (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:1063434)
    at ChildProcess.<anonymous> (C:\Users\mkumar\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:14:1063640)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)`

**Comment by nuclearmistake** [comment]
Same issue here on Windows 10

**Comment by marcelloinfoweb** [comment]
Same problem!!!

Mac OS Catalina

**Comment by rithinskaria** [comment]
Same issue in W10

```
The "path" argument must be of type string. Received type undefined
Hide Stack Trace
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.resolve (path.js:136:9)
    at Object.<anonymous> (file:///C:/Users/riskaria/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at Object.<anonymous> (file:///C:/Users/riskaria/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/riskaria/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:147503)
    at Object.value [as .coffee] (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/riskaria/AppData/Local/atom/app-1.48.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:146819)
    at Object.<anonymous> (file:///C:/Users/riskaria/.atom/packages/remote-edit/lib/main.coffee:3:20)
    at Object.<anonymous> (file:///C:/Users/riskaria/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/riskaria/.atom/packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:147503)
    at Object.value [as .coffee] (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/riskaria/AppData/Local/atom/app-1.48.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3308385)
    at C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3294925
    at Package.measure (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3293757)
    at Package.load (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:3294498)
    at PackageManager.loadAvailablePackage (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:381522)
    at C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:379945
    at Config.transact (C:\Users\riskaria\AppData\Local\atom\app-1.48.0\resources\app\static\<embedded>:11:332010)
```

**Comment by maxreisner** [comment]
Same with Mac OS Catalina

**Comment by aminozuur** [comment]
macOS Big Sur, same issue

**Comment by mohach** [comment]
same issue on manjaro i3

**Comment by ctshh** [comment]
same issue here (and, as that hasn't been said, thanks for the package ;)


**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package 1.9.0


### Stack Trace

Failed to load the remote-edit package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.resolve (path.js:978:7)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:7:36)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at /packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at /packages/remote-edit/lib/main.coffee:3:20)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at /packages/remote-edit/lib/main.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3195184)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3181724
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3180556)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3181297)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381516)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380244)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382816)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:915527
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:910133)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1089018)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1089106
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087774)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
```

### Non-Core Packages

```
print-code 0.7.1 
remote-edit 1.9.0 
script 3.26.0 
teletype 0.13.4 
```

**Comment by alonextou** [comment]
Is this plugin dead or Atom died?

**Comment by gulliverrr** [comment]
> > remote-edit-ni is the one you should now use.
> 
> Unfortunetly, remote-edit-ni don't support ssh keys authorisation :-(

@Shesoff it looks like it does (now), so for me, `remote-edit-ni` looks like a fine replacement!

**Comment by abnerrizzi** [comment]
> Is this plugin dead or Atom died?
looks like =(
