### ISSUE TITLE
Uncaught SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by reggi** [sveale/remote-edit#69]
I was just trying to test https://github.com/sveale/remote-edit/issues/63#issuecomment-87226969 and got an error.

[Enter steps to reproduce below:]

1. tried to create new host ftp

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [remote-edit](git://github.com/sveale/remote-edit) package, v1.7.2

### Stack Trace

Uncaught SyntaxError: Unexpected number

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fthomas%2FDesktop%2Fftp-test%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.188.0%22%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fthomas%2FDesktop%2Fftp-test%22%5D%7D:1

SyntaxError: Unexpected number
    at Object.parse (native)
    at /Users/thomas/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:93:54
    at fs.js:337:14
    at FSReqWrap.oncomplete (fs.js:100:15)
```

### Commands

```
     -0:05.6 core:backspace (atom-text-editor.editor.mini)
     -0:05.0 core:confirm (atom-text-editor.editor.mini)
     -0:03.6 command-palette:toggle (atom-text-editor.editor)
     -0:01.9 core:move-down (atom-text-editor.editor.mini)
     -0:01.2 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 remote-edit:new-host-ftp (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "wrap-guide",
      "autocomplete",
      "autosave",
      "background-tips",
      "bookmarks",
      "jsformat",
      "language-jsx",
      "language-ejs",
      "atom-prettify",
      "autocomplete-plus",
      "autocomplete-plus-async",
      "eval",
      "react",
      "term2",
      "autocomplete-paths"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
language-liquid, v0.2.0
monokai, v0.9.0
remote-edit, v1.7.2

# Dev
No dev packages
```

**Comment by sveale** [comment]
Hmm it works fine here. Can you try deleting ~/.atom/remoteEdit.json and ensure that you're using the latest version?
