### ISSUE TITLE
Browse Hosts command failed with error: Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kurmanka** [sveale/remote-edit#71]
/Users/iku/.atom/packages/remote-edit/lib/main.coffee:87
```
TypeError: undefined is not a function
  at Object.module.exports.browse (/Users/iku/.atom/packages/remote-edit/lib/main.coffee:87:10)
  at atom-workspace.<anonymous> (/Users/iku/.atom/packages/remote-edit/lib/main.coffee:55:67)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:159:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)
```
remote-edit has just been updated to version 1.7.2 from 1.6.something.

**Comment by kurmanka** [comment]
The error has disappeared after an Atom restart.
