### ISSUE TITLE
Uncaught TypeError: Cannot read property 'serialize' of null

### ISSUE THREAD

**Issue by bturrubiates** [sveale/remote-edit#76]
I can't determine what is causing this. When using remote-edit certain files cause this issue. There doesn't seem to be anything interesting about their names or permissions. I've opened these files in remote-edit before, but I recently upgraded atom. 

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [remote-edit](git://github.com/sveale/remote-edit) package, v1.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'serialize' of null

```
At /Users/bturrubi/.atom/packages/remote-edit/lib/view/files-view.coffee:194

TypeError: Cannot read property 'serialize' of null
    at FilesView.module.exports.FilesView.openFile (/Users/bturrubi/.atom/packages/remote-edit/lib/view/files-view.coffee:313:177)
    at FilesView.openFile (/Users/bturrubi/.atom/packages/remote-edit/lib/view/files-view.coffee:3:61)
    at FilesView.module.exports.FilesView.confirmed (/Users/bturrubi/.atom/packages/remote-edit/lib/view/files-view.coffee:328:21)
    at FilesView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
  5x -0:27.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:20.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:19.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:page-down (atom-text-editor.editor.mini.is-focused)
 11x -0:18.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:16.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.3.0 remote-edit:browse (atom-text-editor.editor)
  3x -0:08.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -0:08.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:05.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:04.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
clang-format, v1.13.0
remote-edit, v1.8.0

# Dev
No dev packages
```

**Comment by blacRose** [comment]
# Doing a +1 on this one!

**Comment by sveale** [comment]
Should be fixed now.
Let me know if you're still experiencing issues :)
