### ISSUE TITLE
Bug: after updating, when selecting browse hosts, it shows Emiter has been disposed

### ISSUE THREAD

**Issue by xpl0iter** [sveale/remote-edit#85]
I updated this to the ;atest version today and it has been giving me this error ever since. Here is the stack trace:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [remote-edit](git://github.com/sveale/remote-edit) package, v1.8.3

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:34

Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:34:15)
  at InterProcessDataWatcher.module.exports.InterProcessDataWatcher.onDidChange (C:\Users\Plato P\.atom\packages\remote-edit\lib\model\inter-process-data-watcher.coffee:88:16)
  at HostsView.module.exports.HostsView.initialize (C:\Users\Plato P\.atom\packages\remote-edit\lib\view\hosts-view.coffee:19:30)
  at HostsView.View (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at HostsView.SelectListView (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:18:51)
  at new HostsView (C:\Users\Plato P\.atom\packages\remote-edit\lib\view\hosts-view.coffee:13:5)
  at Object.module.exports.browse (C:\Users\Plato P\.atom\packages\remote-edit\lib\main.coffee:101:16)
  at atom-workspace.<anonymous> (C:\Users\Plato P\.atom\packages\remote-edit\lib\main.coffee:70:67)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\Plato P\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -7:16 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:18.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -6:18 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -6:12.7.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:59.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:59.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:47.8.0 settings-view:uninstall-packages (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:00.1.0 remote-edit:browse (button.btn.btn-default.icon.icon-link-external)
     -0:46.7.0 remote-edit:new-host-ftp (atom-pane.pane.active)
     -0:32 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:26.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:24.7.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -0:12.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP"
    ]
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.3

# Dev
No dev packages
```
\

**Comment by sveale** [comment]
Have you tried reinstalling it?
Does this occur when you select a host for browsing?

**Comment by wolfadex** [comment]
It occurs when pressing Cmd+Shift+P and selecting "Remote Edit: Browse", before I am able to select a host.

It works again after reinstalling.

**Comment by sveale** [comment]
Good to hear :)

**Comment by xpl0iter** [comment]
It didn't fix the issue for me!

**Comment by sveale** [comment]
Have you reinstalled the package?

**Comment by xpl0iter** [comment]
Yes.
