### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by lecraeman** [sveale/remote-edit#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.13

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
    at InterProcessDataWatcher.module.exports.InterProcessDataWatcher.onDidChange (/Users/kenpounders/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:117:27)
    at HostsView.module.exports.HostsView.initialize (/Users/kenpounders/.atom/packages/remote-edit/lib/view/hosts-view.coffee:33:38)
    at HostsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at HostsView.SelectListView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
    at new HostsView (/Users/kenpounders/.atom/packages/remote-edit/lib/view/hosts-view.coffee:24:46)
    at Object.module.exports.browse (/Users/kenpounders/.atom/packages/remote-edit/lib/main.coffee:143:14)
    at atom-workspace.<anonymous> (/Users/kenpounders/.atom/packages/remote-edit/lib/main.coffee:96:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
```

### Commands

```
     -2:13.6.0 remote-edit:browse (ul.list-inline.tab-bar.inset-panel)
  2x -2:13 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:09.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:08.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:08.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:11.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:07.1.0 remote-edit:browse (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
file-icons, v1.5.8
linter, v1.2.4
linter-js-yaml, v1.1.1
remote-edit, v1.8.13

# Dev
No dev packages
```

**Comment by lecraeman** [comment]
Upon restart it appears to be working again just fine. Probably had to do with an update I did!

I'll leave it here, but if you want to close it go ahead...

**Comment by sveale** [comment]
Good to hear :)

**Comment by sterndata** [comment]
Same issue. Atom has to be closed following the update.
